###########################
# SETTINGS FOR SHINYPROXY #
###########################
proxy:
  ##########################
  # DO NOT CHANGE ANYTHING #
  ##########################
  title: San Camillo Apps
  logo-url: file:///opt/shinyproxy/templates/assets/img/logo_sc/sancamillo_logo_white.png
  port: 8080
  template-path: ./templates/
  authentication: none
  admin-groups: admins
  docker:
      internal-networking: true
  template-groups:
    - id: clinical
      properties:
        display-name: Clinical Support
        display-name_it: Supporto Clinico
    - id: scientific
      properties:
        display-name: Scientific Communication
        display-name_it: Lavori Scientifici

# External files
# spring:
#   config:
#     import:
#       - users.yml

  ###############################
  # CHANGE HERE TO ADD NEW APPS #
  ###############################
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/01_hello.png
    template-group: clinical
    template-properties:
      author: ShinyProxy
      doi: 123/456
  - id: MOCAv3
    display-name: MOCA v3
    description: Normative data for MOCA considering Age, Education, CRI, and Sex.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/mocav3')"]
    container-image: shinyapp-mocav3
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/MOCAv3.png
    template-group: clinical
    template-properties:
      author: Giorgio Arcara
      contact: giorgio.arcara@hsancamillo.it
      doi: 10.3390/brainsci8070126
      description_it: Data normativi per MOCA considerando Età, Educazione, CRI e Sesso.
  - id: erp-kw-osc
    display-name: ERP oscillation
    description: A beautiful description.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/erp-kw-osc')"]
    container-image: shinyapp-erpkwosc
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/ERP_KW_OSC_PSC.png
    template-group: scientific
    template-properties:
      author: Sara Lago
      contact: sara.lago@hsancamillo.it
  - id: gamm
    display-name: GAMM age education aperiodic
    description: Another beautiful description.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/gamm')"]
    container-image: shinyapp-gamm
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/GAMM.png
    template-group: scientific
    template-properties:
      author: Sara Lago
      contact: sara.lago@hsancamillo.it


logging:
  file:
    name: shinyproxy.log
