###########################
# SETTINGS FOR SHINYPROXY #
###########################
proxy:
  ##########################
  # DO NOT CHANGE ANYTHING #
  ##########################
  title: San Camillo Apps
  logo-url: file:///opt/shinyproxy/templates/assets/img/logo_sc/sancamillo_logo_white.png
  port: 8080
  template-path: ./templates/
  authentication: none
  admin-groups: admins
  # users:
  # - name: jack
  #   password: password
  #   groups: admins
  # - name: jeff
  #   password: password
  docker:
      internal-networking: true

  ###############################
  # CHANGE HERE TO ADD NEW APPS #
  ###############################
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/01_hello.png
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-nw
    logo-url: /assets/img/apps/06_tabsets.png
  - id: MOCAv3
    docker-cmd: ["R", "-e", "shiny::runApp('/root/mocav3')"]
    container-image: shinyapp-mocav3
    container-network: shinyproxy-nw
  - id: euler
    docker-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: shinyapp-euler
    container-network: shinyproxy-nw
  - id: erp-kw-osc
    docker-cmd: ["R", "-e", "shiny::runApp('/root/erp-kw-osc')"]
    container-image: shinyapp-erpkwosc
    container-network: shinyproxy-nw
  - id: gamm
    docker-cmd: ["R", "-e", "shiny::runApp('/root/gamm')"]
    container-image: shinyapp-gamm
    container-network: shinyproxy-nw


logging:
  file:
    name: shinyproxy.log
